# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "cancun"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  script = "script"
  solc = "0.8.28"
  src = "src"
  test = "test"
  ffi = true
  ast = true
  build_info = true
  extra_output = ["storageLayout"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  optimism_sepolia = { key = "${API_KEY_ETHERSCAN_OPTIMISM}" }
  optimism = { key = "${API_KEY_ETHERSCAN_OPTIMISM}" }
  polygon_mumbai = { key = "${API_KEY_ETHERSCAN_POLYGON}" }
  polygon = { key = "${API_KEY_ETHERSCAN_POLYGON}" }
  base-sepolia = { key = "${API_KEY_ETHERSCAN_BASE}" }
  base = { key = "${API_KEY_ETHERSCAN_BASE}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  sepolia = "${SEPOLIA_RPC_URL}"
  optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
  polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"
  optimism = "${OPTIMISM_RPC_URL}"
  base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
  base = "${BASE_RPC_URL}"
